"""Django settings for django_starter project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

import dj_database_url

from django.utils.translation import ugettext_lazy as _


################
#
# COMMON PATHS
#
################
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
CONF_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(CONF_DIR)


################
#
# GENERAL SETTINGS
#
################
# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/
LANGUAGES = (
    ('fr', _('Francais')),
    ('en', _('Anglais')),
)
LANGUAGE_CODE = 'fr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
# Redirection page after login
LOGIN_REDIRECT_URL = '/'


################
#
# APPLICATIONS
#
################
# Default Applications
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# Third party apps
INSTALLED_APPS += [
]

# Our apps
INSTALLED_APPS += [
    'django_application.apps.core',
]

################
#
# MIDDLEWARE
#
################
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


################
#
# URL AND WSGI CONFIG
#
################
ROOT_URLCONF = 'django_application.conf.urls'
WSGI_APPLICATION = 'django_application.conf.wsgi.application'


################
#
# TEMPLATE
#
################
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['django_application/apps/core/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


################
#
# STATIC
#
################
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
# WhiteNoise config
# http://whitenoise.evans.io/en/stable/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
# Extra places for collectstatic to find static files.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Simplified static file serving.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


################
#
# DATABASE
#
################
# Django doc: https://docs.djangoproject.com/en/1.10/ref/settings/#databases
# Psql doc: https://www.postgresql.org/docs/9.4/static/sql-createrole.html
# Use dj-database-url to set the database setting
DATABASES = {}
DATABASES['default'] = dj_database_url.config(conn_max_age=600)
